Repository kartoza/africa_rangeland_watch, pull requests merged in 2024-12, with the labels that each got.

#143 Update home page
  docs/mkdocs-html.yml
  docs/src/img/arw-logo-1.svg
  docs/src/img/home-page-img-1.png
  docs/src/index.md
Labels: documentation, Size 3

#142 Fix current site bugs
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/RequestOrganisation/index.tsx
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/pages/Dashboard/index.tsx
  django_project/frontend/src/pages/Home/index.tsx
  django_project/frontend/src/pages/Support/index.tsx
  django_project/frontend/src/store/authSlice.ts
  django_project/frontend/src/store/organizationSlice.ts
  django_project/frontend/src/store/ticketSlice.ts
  django_project/frontend/src/utils/csrfUtils.ts
  django_project/support/views.py
Labels: bug, Size 3

#124 Onboarding workflow
  docs/src/user/img/user-workflow-img-1.png
  docs/src/user/img/user-workflow-img-2.png
  docs/src/user/img/user-workflow-img-3.png
  docs/src/user/index.md
  docs/src/user/onboard.md
Labels: documentation, Size 5

#150 patch: update variables in template
  django_project/base/admin.py
  django_project/core/resend_email_backend.py
  django_project/core/templates/account/email_confirmation.html
Labels: bug, Size 2

#152 patch: fix incorrect authentication urls
  django_project/base/templates/join_organization_request.html
  django_project/core/custom_auth_view.py
Labels: bug

#154 Add GitHub login
  deployment/docker/requirements.txt
  django_project/core/custom_auth_view.py
  django_project/core/settings/base.py
  django_project/core/settings/contrib.py
  django_project/core/urls.py
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: Size 2

#166 patch: set user verified to true
  django_project/core/custom_auth_view.py
  django_project/core/templates/account/email_confirmation.html
Labels: Size 1, Development

#163 Implement uploaded resources page
  django_project/core/urls.py
  django_project/frontend/src/pages/UploadedResources/index.tsx
  django_project/frontend/src/store/layerSlice.ts
  django_project/layers/tests/test_views.py
  django_project/layers/urls.py
  django_project/layers/views.py
Labels: Size 3

#169 Fix authentication failing
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/MegaMenu/index.tsx
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: bug

#153 Add google login
  django_project/core/settings/contrib.py
  django_project/frontend/src/components/SignIn.tsx
Labels: Size 2

#171 Update ticketSlice.ts
  django_project/core/settings/base.py
  django_project/core/settings/contrib.py
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/src/store/organizationSlice.ts
  django_project/frontend/src/store/ticketSlice.ts
  django_project/support/templates/new_ticket_notification.html
Labels: bug, Size 2

#174 patch: adjust footer styling
  django_project/frontend/src/components/Footer/index.tsx
Labels: Size 1

#172 Add learn more page
  django_project/frontend/public/Herding.for.Health.pdf
  django_project/frontend/public/dashboard/dashboard_image3.svg
  django_project/frontend/public/images/learn_more_health.svg
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/MegaMenu/index.tsx
  django_project/frontend/src/pages/About/LearnMore.tsx
  django_project/frontend/src/pages/Home/index.tsx
Labels: Size 2

#176 patch: set auto sign up to true
  django_project/core/settings/contrib.py
  django_project/frontend/src/store/authSlice.ts
Labels: Size 1

#164 Make users belong to multiple organisations
  django_project/base/admin.py
  django_project/base/migrations/0005_remove_userprofile_organisation_and_more.py
  django_project/base/models.py
  django_project/base/test_views.py
  django_project/base/views.py
  django_project/frontend/src/pages/OrganisationInformation/index.tsx
Labels: Size 3

#180 patch: retrieve issue types from results
  django_project/core/settings/contrib.py
  django_project/frontend/src/store/ticketSlice.ts
Labels: bug

#181 Implement profile page
  deployment/docker/requirements.txt
  django_project/base/admin.py
  django_project/base/migrations/0006_userprofile_profile_image.py
  django_project/base/models.py
  django_project/base/organisation_views.py
  django_project/base/serializers.py
  django_project/base/tests/analytics_icon.svg
  django_project/base/tests/test_organisation_views.py
  django_project/base/tests/test_userprofile_views.py
  django_project/base/urls.py
  django_project/base/user_profile_views.py
  django_project/frontend/src/components/ChangePassword.tsx
  django_project/frontend/src/components/RequestOrganisation/index.tsx
  django_project/frontend/src/pages/Profile/index.tsx
  django_project/frontend/src/store/index.ts
  django_project/frontend/src/store/userProfileSlice.ts
Labels: Size 8, Development

#177 Update map and sign-up docs
  docs/src/user/guide/img/guide-map-img-10.png
  docs/src/user/guide/img/guide-map-img-11.png
  docs/src/user/guide/img/guide-map-img-12.png
  docs/src/user/guide/img/guide-map-img-13.png
  docs/src/user/guide/img/guide-map-img-14.png
  docs/src/user/guide/img/guide-map-img-15.png
  docs/src/user/guide/img/guide-map-img-16.png
  docs/src/user/guide/img/guide-map-img-7.png
  docs/src/user/guide/img/guide-signup-img-6.png
  docs/src/user/guide/img/guide-signup-img-7.png
  docs/src/user/guide/img/guide-signup-img-8.png
  docs/src/user/guide/map.md
  docs/src/user/guide/sign-up.md
  docs/src/user/manual/img/landing-page-img-3.png
  docs/src/user/manual/img/manual-map-img-14.png
  docs/src/user/manual/img/manual-map-img-15.png
  docs/src/user/manual/img/manual-map-img-16.png
  docs/src/user/manual/img/manual-map-img-17.png
  docs/src/user/manual/img/manual-map-img-18.png
  docs/src/user/manual/img/manual-map-img-19.png
  docs/src/user/manual/img/manual-map-img-20.png
  docs/src/user/manual/img/manual-map-img-21.png
  docs/src/user/manual/img/signup-img-5.png
  docs/src/user/manual/img/signup-img-6.png
  docs/src/user/manual/img/signup-img-7.png
  docs/src/user/manual/map.md
  docs/src/user/manual/sign-up.md
Labels: documentation, Size 5
