Repository kartoza/africa_rangeland_watch, pull requests merged in 2024-11, with the labels that each got.

#32 Add theme provider and main page
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/public/dashboard/dashboard_image1.svg
  django_project/frontend/public/fonts/InterBold.ttf
  django_project/frontend/public/fonts/InterRegular.ttf
  django_project/frontend/public/fonts/readme.md
  django_project/frontend/public/images/arrow_down.svg
  django_project/frontend/public/images/down_arrow.svg
  django_project/frontend/public/images/main_logo.svg
  django_project/frontend/public/images/notifications_icon.svg
  django_project/frontend/public/images/search_icon.svg
  django_project/frontend/public/images/user_avatar_header_icon.svg
  django_project/frontend/public/logo192.png
  django_project/frontend/public/logo512.png
  django_project/frontend/public/manifest.json
  django_project/frontend/src/App.tsx
  django_project/frontend/src/Home.tsx
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/ErrorBoundary.tsx
  django_project/frontend/src/components/Footer/index.tsx
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/MegaMenu/index.tsx
  django_project/frontend/src/index.js
  django_project/frontend/src/index.tsx
  django_project/frontend/src/logo.svg
  django_project/frontend/src/pages/Home.tsx
  django_project/frontend/src/pages/Home/index.tsx
  django_project/frontend/src/pages/NotFound.tsx
  django_project/frontend/src/styles/App.scss
  django_project/frontend/src/styles/font.css
  django_project/frontend/src/styles/index.css
  django_project/frontend/src/styles/index.scss
  django_project/frontend/src/theme/components/button.ts
  django_project/frontend/src/theme/components/heading.ts
  django_project/frontend/src/theme/components/index.ts
  django_project/frontend/src/theme/components/text.ts
  django_project/frontend/src/theme/foundations/colors.ts
  django_project/frontend/src/theme/foundations/fonts.ts
  django_project/frontend/src/theme/foundations/index.ts
  django_project/frontend/src/theme/foundations/shadows.ts
  django_project/frontend/src/theme/index.ts
Labels: Size 8

#36 Add sign in page
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/pages/Home/index.tsx
Labels: Size 5

#37 feat: centralise sign in sign up and forgot password
  django_project/frontend/public/images/eye_icon_unchecked.svg
  django_project/frontend/public/images/logged_in_user_avatar.svg
  django_project/frontend/src/components/SignIn.tsx
Labels: Size 5

#51 update postgis
  deployment/docker-compose.yml
Labels: Size 1

#54 Add organisation page
  django_project/frontend/package.json
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/SideBar/index.tsx
  django_project/frontend/src/pages/Home.tsx
  django_project/frontend/src/pages/OrganisationInformation/index.tsx
Labels: Size 5

#58 Implement login functionality
  deployment/docker/requirements.txt
  django_project/core/custom_auth_view.py
  django_project/core/settings/contrib.py
  django_project/core/urls.py
  django_project/frontend/package.json
  django_project/frontend/src/App.tsx
  django_project/frontend/src/PrivateRoute.tsx
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/store/authSlice.ts
  django_project/frontend/src/store/index.ts
Labels: Size 8

#68 Add analysis results page
  django_project/core/settings/contrib.py
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/SideBar/AnalysisSideBar.tsx
  django_project/frontend/src/components/SideBar/index.tsx
  django_project/frontend/src/pages/AnalysisResults/index.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: Size 5

#76 Add uploaded resources page
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/SideBar/index.tsx
  django_project/frontend/src/pages/UploadedResources/index.tsx
Labels: Size 3

#80 Make notifications page
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/SideBar/index.tsx
  django_project/frontend/src/pages/Notifications/index.tsx
  django_project/frontend/src/pages/Notifications/notificationsTab.tsx
  django_project/frontend/src/pages/Notifications/systemTab.tsx
Labels: Size 5

#83 Landing page docs
  docs/src/user/manual/img/landing-page-img-1.png
  docs/src/user/manual/img/landing-page-img-2.png
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/signup-signin/forgot-password.md
  docs/src/user/manual/signup-signin/img/forgot-password-img-1.png
  docs/src/user/manual/signup-signin/img/forgot-password-img-2.png
  docs/src/user/manual/signup-signin/img/forgot-password-img-3.png
  docs/src/user/quickstart/img/quickstart-img-1.png
  docs/src/user/quickstart/img/quickstart-img-2.png
  docs/src/user/quickstart/img/quickstart-img-3.png
  docs/src/user/quickstart/img/quickstart-img-4.png
  docs/src/user/quickstart/img/quickstart-img-5.png
  docs/src/user/quickstart/img/quickstart-img-6.png
  docs/src/user/quickstart/img/quickstart-img-7.png
  docs/src/user/quickstart/img/quickstart-img-8.png
  docs/src/user/quickstart/img/quickstart-img-9.png
  docs/src/user/quickstart/index.md
Labels: documentation, Size 5

#88 Add support page
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/RequestOrganisation/index.tsx
  django_project/frontend/src/components/SideBar/index.tsx
  django_project/frontend/src/pages/Support/index.tsx
Labels: Size 5

#90 Implement support
  deployment/.template.env
  django_project/base/migrations/0003_userprofile_is_support_staff.py
  django_project/base/models.py
  django_project/core/settings/project.py
  django_project/core/urls.py
  django_project/frontend/src/components/SideBar/index.tsx
  django_project/frontend/src/pages/Support/index.tsx
  django_project/frontend/src/store/authSlice.ts
  django_project/frontend/src/store/index.ts
  django_project/frontend/src/store/ticketSlice.ts
  django_project/support/__init__.py
  django_project/support/admin.py
  django_project/support/apps.py
  django_project/support/migrations/0001_initial.py
  django_project/support/migrations/0002_issuetype_ticket_issue_type.py
  django_project/support/migrations/__init__.py
  django_project/support/models.py
  django_project/support/serializers.py
  django_project/support/templates/alert_ticket_notification.html
  django_project/support/templates/new_ticket_notification.html
  django_project/support/templates/ticket_details.html
  django_project/support/templates/ticket_status_update.html
  django_project/support/tests/__init__.py
  django_project/support/tests/test_models.py
  django_project/support/tests/test_serializers.py
  django_project/support/tests/test_views.py
  django_project/support/urls.py
  django_project/support/views.py
Labels: Size 8

#98 Map functionality doc
  docs/src/user/guide/img/guide-map-img-1.png
  docs/src/user/guide/img/guide-map-img-2.png
  docs/src/user/guide/img/guide-map-img-3.png
  docs/src/user/guide/img/guide-map-img-4.png
  docs/src/user/guide/img/guide-map-img-5.png
  docs/src/user/guide/img/guide-map-img-6.png
  docs/src/user/guide/img/guide-map-img-7.png
  docs/src/user/guide/img/guide-map-img-8.png
  docs/src/user/guide/img/guide-map-img-9.png
  docs/src/user/guide/index.md
  docs/src/user/guide/map.md
  docs/src/user/index.md
  docs/src/user/manual/img/manual-map-img-1.png
  docs/src/user/manual/img/manual-map-img-10.png
  docs/src/user/manual/img/manual-map-img-11.png
  docs/src/user/manual/img/manual-map-img-12.png
  docs/src/user/manual/img/manual-map-img-13.png
  docs/src/user/manual/img/manual-map-img-2.png
  docs/src/user/manual/img/manual-map-img-3.png
  docs/src/user/manual/img/manual-map-img-4.png
  docs/src/user/manual/img/manual-map-img-5.png
  docs/src/user/manual/img/manual-map-img-6.png
  docs/src/user/manual/img/manual-map-img-7.png
  docs/src/user/manual/img/manual-map-img-8.png
  docs/src/user/manual/img/manual-map-img-9.png
  docs/src/user/manual/index.md
  docs/src/user/manual/map.md
Labels: documentation, Size 8

#94 Implement registration
  django_project/core/custom_auth_view.py
  django_project/core/settings/contrib.py
  django_project/core/templates/account/email_confirmation.html
  django_project/core/templates/account/password_reset_email.html
  django_project/core/test_views.py
  django_project/core/urls.py
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/pages/Home/index.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: Size 5

#103 Create about page
  django_project/frontend/public/dashboard/dashboard_image2.svg
  django_project/frontend/public/images/analytics_icon.svg
  django_project/frontend/public/images/dashboard_and_reports.svg
  django_project/frontend/public/images/interactive_map_icon.svg
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/Footer/index.tsx
  django_project/frontend/src/pages/About/index.tsx
Labels: Size 5

#106 patch: add csrf token to all requests
  django_project/base/admin.py
  django_project/frontend/src/components/MegaMenu/index.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: Size 1

#119 About page doc
  docs/src/user/manual/about.md
  docs/src/user/manual/img/about-img-1.png
  docs/src/user/manual/img/about-img-2.png
  docs/src/user/manual/img/about-img-3.png
  docs/src/user/manual/img/about-img-4.png
  docs/src/user/manual/img/about-img-5.png
  docs/src/user/manual/img/about-img-6.png
  docs/src/user/manual/img/about-img-7.png
Labels: documentation, Size 5

#109 Implement organisation on boarding (onboarding 3)
  django_project/base/forms.py
  django_project/base/models.py
  django_project/base/templates/invitation_to_join_organization.html
  django_project/base/test_views.py
  django_project/base/tests.py
  django_project/base/urls.py
  django_project/base/views.py
  django_project/core/settings/project.py
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/components/inviteMembers.tsx
  django_project/frontend/src/pages/Home/index.tsx
  django_project/frontend/src/pages/OrganisationInformation/index.tsx
  django_project/frontend/src/store/index.ts
  django_project/frontend/src/store/organizationSlice.ts
Labels: Size 13

#112 Update PrivateRoute.tsx
  django_project/frontend/src/PrivateRoute.tsx
  django_project/frontend/src/pages/About/index.tsx
  django_project/frontend/src/pages/Home/index.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: Size 2

#128 Add resend backend
  deployment/.template.env
  django_project/core/custom_auth_view.py
  django_project/core/resend_email_backend.py
  django_project/core/settings/base.py
  django_project/core/settings/dev.py
  django_project/core/settings/prod.py
Labels: Size 2

#123 Add resources page
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/MegaMenu/index.tsx
  django_project/frontend/src/pages/AnalysisResults/index.tsx
  django_project/frontend/src/pages/Resources/index.tsx
  django_project/frontend/src/pages/UploadedResources/index.tsx
Labels: Size 3

#122 Implement organisation on boarding (onboarding 2)
  django_project/base/admin.py
  django_project/base/migrations/0004_organisationinvitation_metadata_and_more.py
  django_project/base/models.py
  django_project/base/templates/accepted_organization_request.html
  django_project/base/templates/join_organization_request.html
  django_project/base/templates/organization_manager_notification.html
  django_project/base/templates/request_to_add_organization.html
  django_project/base/test_views.py
  django_project/base/urls.py
  django_project/base/views.py
  django_project/frontend/src/components/RequestOrganisation/index.tsx
Labels: Size 8

#138 Add dashboard page
  django_project/frontend/public/images/toggle_icon.svg
  django_project/frontend/src/Routes.tsx
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/Pagination.tsx
  django_project/frontend/src/pages/Dashboard/index.tsx
  django_project/frontend/src/styles/pagination.css
Labels: Size 5

#141 Fix email templates
  django_project/base/admin.py
  django_project/base/models.py
  django_project/base/views.py
  django_project/core/custom_auth_view.py
  django_project/support/models.py
Labels: bug, Size 2
