Repository kartoza/africa_rangeland_watch, pull requests merged in 2025-02, with the labels that each got.

#268 Multiple updates
  docs/src/user/guide/about.md
  docs/src/user/guide/img/guide-about-img-5.png
  docs/src/user/guide/img/guide-map-img-19.png
  docs/src/user/guide/img/guide-map-img-2.png
  docs/src/user/guide/img/guide-map-img-20.png
  docs/src/user/guide/img/guide-map-img-21.png
  docs/src/user/guide/img/guide-map-img-22.png
  docs/src/user/guide/img/guide-map-img-23.png
  docs/src/user/guide/img/guide-map-img-3.png
  docs/src/user/guide/img/guide-map-img-4.png
  docs/src/user/guide/map.md
  docs/src/user/manual/about.md
  docs/src/user/manual/img/about-img-6.png
  docs/src/user/manual/img/manual-map-img-14.png
  docs/src/user/manual/img/manual-map-img-2.png
  docs/src/user/manual/img/manual-map-img-24.png
  docs/src/user/manual/img/manual-map-img-25.png
  docs/src/user/manual/img/manual-map-img-26.png
  docs/src/user/manual/img/manual-map-img-27.png
  docs/src/user/manual/img/manual-map-img-28.png
  docs/src/user/manual/img/manual-map-img-3.png
  docs/src/user/manual/img/manual-map-img-4.png
  docs/src/user/manual/map.md
Labels: documentation, Size 5

#301 patch: add pdf and html canvas packages
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/src/components/ChartCard.tsx
Labels: Development

#275 Analysis result doc
  docs/src/user/guide/img/guide-analysis-img-1.png
  docs/src/user/guide/img/guide-map-img-10.png
  docs/src/user/guide/img/guide-map-img-11.png
  docs/src/user/guide/img/guide-map-img-12.png
  docs/src/user/guide/img/guide-map-img-13.png
  docs/src/user/guide/img/guide-map-img-17.png
  docs/src/user/guide/img/guide-map-img-24.png
  docs/src/user/guide/img/guide-map-img-6.png
  docs/src/user/guide/img/guide-map-img-8.png
  docs/src/user/guide/img/guide-map-img-9.png
  docs/src/user/guide/map.md
  docs/src/user/manual/Analysis-result.md
  docs/src/user/manual/img/analysis-results-img-1.png
  docs/src/user/manual/img/manual-map-img-14.png
  docs/src/user/manual/img/manual-map-img-15.png
  docs/src/user/manual/img/manual-map-img-16.png
  docs/src/user/manual/img/manual-map-img-17.png
  docs/src/user/manual/img/manual-map-img-24.png
  docs/src/user/manual/img/manual-map-img-26.png
  docs/src/user/manual/img/manual-map-img-28.png
  docs/src/user/manual/img/manual-map-img-29.png
  docs/src/user/manual/img/manual-map-img-6.png
  docs/src/user/manual/img/manual-map-img-7.png
  docs/src/user/manual/map.md
Labels: documentation, Size 5

#309 Dashboards data filtering
  django_project/dashboard/urls.py
  django_project/dashboard/views.py
  django_project/frontend/src/components/DashboardFilters.tsx
  django_project/frontend/src/pages/Dashboard/index.tsx
  django_project/frontend/src/store/dashboardSlice.tsx
Labels: Development

#315 patch: add safety checks
  django_project/frontend/src/components/DashboardCharts/CombinedCharts.tsx
Labels: bug
