Repository kartoza/africa_rangeland_watch, pull requests merged in 2025-01, with the labels that each got.

#206 Add social auth docs
  docs/src/user/guide/Organisation-information.md
  docs/src/user/guide/Sign-out.md
  docs/src/user/guide/img/guide-organisation-img-1.png
  docs/src/user/guide/img/guide-organisation-img-2.png
  docs/src/user/guide/img/guide-organisation-img-3.png
  docs/src/user/guide/img/guide-signin-img-10.png
  docs/src/user/guide/img/guide-signin-img-7.png
  docs/src/user/guide/img/guide-signin-img-8.png
  docs/src/user/guide/img/guide-signin-img-9.png
  docs/src/user/guide/img/guide-signup-img-10.png
  docs/src/user/guide/img/guide-signup-img-9.png
  docs/src/user/guide/sign-in.md
  docs/src/user/guide/sign-up.md
  docs/src/user/manual/Organisation-information.md
  docs/src/user/manual/img/organisation-info-img-1.png
  docs/src/user/manual/img/organisation-info-img-2.png
  docs/src/user/manual/img/signin-img-4.png
  docs/src/user/manual/img/signin-img-5.png
  docs/src/user/manual/img/signin-img-6.png
  docs/src/user/manual/img/signin-img-7.png
  docs/src/user/manual/img/signup-img-10.png
  docs/src/user/manual/img/signup-img-11.png
  docs/src/user/manual/img/signup-img-12.png
  docs/src/user/manual/img/signup-img-8.png
  docs/src/user/manual/img/signup-img-9.png
  docs/src/user/manual/sign-in.md
  docs/src/user/manual/sign-up.md
Labels: documentation, Size 5

#209 Add upload shape file docs
  docs/src/user/guide/img/guide-map-img-17.png
  docs/src/user/guide/img/guide-map-img-18.png
  docs/src/user/guide/img/guide-map-img-2.png
  docs/src/user/guide/img/guide-map-img-3.png
  docs/src/user/guide/img/guide-map-img-4.png
  docs/src/user/guide/img/guide-map-img-5.png
  docs/src/user/guide/img/guide-map-img-6.png
  docs/src/user/guide/map.md
  docs/src/user/manual/img/manual-map-img-12.png
  docs/src/user/manual/img/manual-map-img-13.png
  docs/src/user/manual/img/manual-map-img-14.png
  docs/src/user/manual/img/manual-map-img-2.png
  docs/src/user/manual/img/manual-map-img-22.png
  docs/src/user/manual/img/manual-map-img-23.png
  docs/src/user/manual/img/manual-map-img-3.png
  docs/src/user/manual/map.md
Labels: documentation, Size 3

#216 Build fix
  docs/uuid_redirects_hook.py
Labels: bug

#225 patch: add pagination to organisations page
  django_project/frontend/src/pages/OrganisationInformation/index.tsx
Labels: enhancement

#228 remove id param from url
  django_project/base/organisation_views.py
Labels: bug

#222 Enable remember me feature
  django_project/core/custom_auth_view.py
  django_project/core/settings/contrib.py
  django_project/core/test_views.py
  django_project/core/urls.py
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: enhancement

#241 remove contact us section
  django_project/frontend/src/pages/About/index.tsx
Labels: enhancement

#231 allow multiple organisations per user
  django_project/base/admin.py
  django_project/base/migrations/0007_organisationinvitationdetail.py
  django_project/base/migrations/0008_rename_aceepted_organisationinvitationdetail_accepted.py
  django_project/base/migrations/0009_remove_organisationinvitation_metadata_and_more.py
  django_project/base/migrations/0010_alter_organisationinvitationdetail_organisation.py
  django_project/base/migrations/0011_alter_organisationinvitationdetail_invitation.py
  django_project/base/models.py
  django_project/base/organisation_views.py
  django_project/base/tests/test_organisation_views.py
  django_project/frontend/package-lock.json
  django_project/frontend/src/components/RequestOrganisation/index.tsx
Labels: Size 5, Development

#251 create dashboard from analysis
  django_project/analysis/admin.py
  django_project/analysis/migrations/0004_useranalysisresults.py
  django_project/analysis/migrations/0005_alter_useranalysisresults_analysis_results_and_more.py
  django_project/analysis/models.py
  django_project/analysis/serializer.py
  django_project/analysis/urls.py
  django_project/analysis/views.py
  django_project/core/urls.py
  django_project/dashboard/migrations/0004_dashboard_analysis_results.py
  django_project/dashboard/models.py
  django_project/dashboard/tests/test_views.py
  django_project/dashboard/urls.py
  django_project/dashboard/views.py
  django_project/frontend/src/components/CreateDashboard.tsx
  django_project/frontend/src/components/Map/LeftSide/Analysis/index.tsx
  django_project/frontend/src/pages/AnalysisResults/index.tsx
  django_project/frontend/src/store/analysisSlice.ts
  django_project/frontend/src/store/dashboardSlice.tsx
  django_project/frontend/src/store/index.ts
  django_project/frontend/src/store/userAnalysisSlice.ts
Labels: Size 13, Development

#237 implement session continuity
  django_project/core/admin.py
  django_project/core/migrations/0004_usersession.py
  django_project/core/models.py
  django_project/core/serializers.py
  django_project/core/session_views.py
  django_project/core/tests/test_views.py
  django_project/core/urls.py
  django_project/frontend/src/App.tsx
  django_project/frontend/src/components/Header.tsx
  django_project/frontend/src/components/Map/LeftSide/Analysis/index.tsx
  django_project/frontend/src/components/Map/LeftSide/index.tsx
  django_project/frontend/src/components/SessionPrompt.tsx
  django_project/frontend/src/components/SignIn.tsx
  django_project/frontend/src/sessionProvider.tsx
  django_project/frontend/src/store/authSlice.ts
Labels: Size 8

#266 Multiple updates
  docs/mkdocs-base.yml
  docs/src/index.md
Labels: documentation

#274 Implement dashboard visualizations
  django_project/dashboard/serializers.py
  django_project/frontend/package-lock.json
  django_project/frontend/package.json
  django_project/frontend/src/components/ChartCard.tsx
  django_project/frontend/src/components/DashboardCharts/BarChart.tsx
  django_project/frontend/src/components/DashboardCharts/LineChart.tsx
  django_project/frontend/src/components/DashboardCharts/PieChart.tsx
  django_project/frontend/src/pages/Dashboard/index.tsx
Labels: Development

#242 fix invitations not sending
  django_project/base/organisation_views.py
  django_project/base/templates/invitation_to_join_organization.html
  django_project/frontend/src/components/inviteMembers.tsx
  django_project/frontend/src/pages/OrganisationInformation/index.tsx
  django_project/frontend/src/store/organizationSlice.ts
Labels: bug
